name: RestSharp tests

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Api tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./SpecFlow/TestAutomation

    - name: Build project
      run: dotnet build --configuration Release --no-restore
      working-directory: ./SpecFlow/TestAutomation

    - name: Run tests
      run: dotnet test ApiTests/ApiTests.csproj --configuration Release --verbosity normal
      working-directory: ./SpecFlow/TestAutomation