name: Selenium tests
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Selenium UI tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./SpecFlow/TestAutomation

    - name: Show dotnet info
      run: dotnet --info

    - name: Build project
      run: dotnet build --configuration Release --no-restore
      working-directory: ./SpecFlow/TestAutomation

    - name: Run tests
      run: dotnet test SeleniumTests/SeleniumTests.csproj --configuration Release
      working-directory: ./SpecFlow/TestAutomation

    - name: Upload failure screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Upload screenshots
        path: ~/**/TestReport/

        
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: Upload screenshots
        path: ~/**/TestReport/
